services:
  app:
    build:
      context: .
      dockerfile: DockerfileProd
    image: avatarkrd-as:prod
    container_name: avatarkrd-app
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - CONTAINER_ROLE=app
    volumes:
      - .:/var/www
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/up || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - traefik.enable=true

networks:
  dokploy-network:
    external: true

volumes:
  caddy-data:
  caddy-config:
